---
- name: Add backports repository
  apt_repository:
    repo: 'deb http://deb.debian.org/debian bullseye-backports main'
    state: present
    update_cache: true

- name: Install samba packages from OS
  apt:
    default_release: bullseye-backports
    pkg:
      - acl
      - attr
      - dnsutils
      - krb5-user
      - krb5-config
      - libpam-winbind
      - libnss-winbind
      - samba
      - samba-common
      - samba-dsdb-modules
      - samba-vfs-modules
      - winbind
   





