---
- include: hostname.yml

- import_tasks: install.yml
  when: not domain_member_use_backports

- import_tasks: backports_install.yml
  when: domain_member_use_backports

- include: debian.yml
- include: sssd.yml

# REBOOT
#########################################################
# Reiniciar se o arquivo /var/.samba_domain_member NÃO existir

- name: create_domain_member
  stat:
    path: /var/.samba_domain_member
  register: samba_domain_member_check

- name: Reboot immediately if there was a change.
  shell: "sleep 5 && reboot"
  async: 1
  poll: 0
  when: not samba_domain_member_check['stat']['exists']|bool

- name: Wait for the reboot to complete if there was a change.
  wait_for_connection:
    connect_timeout: 20
    sleep: 5
    delay: 5
    timeout: 600
  when: not samba_domain_member_check['stat']['exists']|bool 

- name: Depois do reboot, criar o arquivo /var/.samba_domain_member se ele não existir
  file:
    dest: /var/.samba_domain_member
    state: touch
  when: not samba_domain_member_check['stat']['exists']|bool

#########################################################
