---
- name: install sssd packages
  package:
    name:
      - libnss-winbind
      - sssd
    state: present

- name: template /etc/sssd/sssd.conf
  template:
    src: sssd.conf.j2
    dest:  /etc/sssd/sssd.conf
    owner: root
    group: root
    mode: 0600
   
- name: "Configure nsswitch - passwd"
  lineinfile:
    path: /etc/nsswitch.conf
    regexp: '^passwd:'
    #line: 'passwd:         files sss'
    # winbind inserido por conta do domain member como servidor de impressão
    # verificar se não vai impactar nas máquinas clientes da pró-aluno
    line: 'passwd:         files sss winbind'

- name: "Configure nsswitch - group"
  lineinfile:
    path: /etc/nsswitch.conf
    regexp: '^group:'
    #line: 'group:          files sss'
    line: 'group:          files sss winbind'

- name: "Configure nsswitch - netgroup"
  lineinfile:
    path: /etc/nsswitch.conf
    regexp: 'netgroup:'
    line: 'netgroup:         nis sss'

- name: "Configure PAM Configuration"
  shell: DEBIAN_FRONTEND=noninteractive pam-auth-update

- name: home directory
  lineinfile:
    path: /etc/pam.d/common-session
    line: 'session    required    pam_mkhomedir.so skel=/etc/skel/ umask=0077'

#- name: "Configure PAM - /etc/pam.d/common-password"
#  replace:
#    path: /etc/pam.d/common-password
#    regexp: ' use_authtok'
#    replace: ''

- name: "Update pam"
  shell: "/usr/sbin/pam-auth-update --package"

- name: start sssd on boot
  service: name=sssd state=started enabled=yes

- name: Restart service sssd
  service:
    name: sssd
    state: restarted

- name:  "sudo"
  template:
    src: sudo.j2
    dest: /etc/sudoers.d/domain-admins
    owner: root
    group: root
    mode: 0440