---
- name: "Configure nsswitch - passwd"
  lineinfile:
    path: /etc/nsswitch.conf
    regexp: '^passwd:'
    line: 'passwd:         files systemd winbind'

- name: "Configure nsswitch - group"
  lineinfile:
    path: /etc/nsswitch.conf
    regexp: '^group:'
    line: 'group:          files systemd winbind'
